### ISSUE TITLE
STM32F411xE - use lower sector

### ISSUE THREAD

**Issue by magdkudama** [nimaltd/ee#13]
Hello,

Thanks for this library.

Just a quick question: why do you only allow writing on sectors 5-7 on the device, knowing they're 128Kb each (in my case)? Is it a bad practice to use the lower sectors (say, sector 1, which is 16Kb)?

Thanks!

**Comment by nimaltd** [comment]
Hello. You have to choose the last sector  because your code program into sector 0 to the last

**Comment by magdkudama** [comment]
Thanks for the comment. I guess that's not always true? I have a bootloader on sector 0, and it decides which app will be used (I can have two apps). Both apps live on the higher end of sectors, as they're bigger. So for me it's more interesting to have my data saved in a lower sector. Is that not a valid use-case?

Thanks a lot.

**Comment by nimaltd** [comment]
it is true. if you are using a bootloader. you can use a free sector for eeprom.
