### ISSUE TITLE
"Flash Word" might be 128-bit in some STM32H7 series

### ISSUE THREAD

**Issue by ElluIFX** [nimaltd/ee#27]
I am using the new version of the ee library in my STM32H7B0VBT6 and I noticed that it writes only 16 bytes per operation instead of the expected 32 bytes.

As I mentioned in my title, after checking the datasheet, it says the "Flash Word" is 128bit on my H7B0, so I think more "#if" is required for the writing function for H7.

But I'm not sure if all single-bank H7 follow this special case, it seems that most answers think the flash word is exactly 256-bit for all H7, even the MicroPython [source code](https://github.com/micropython/micropython/blob/master/ports/stm32/flash.c#L465).

Thanks, nice lib, the datasheet I mentioned is as below:

![image](https://github.com/nimaltd/ee/assets/31679332/4bc9d676-0a83-4272-b4d1-13af7ad93c4d)

**Comment by nimaltd** [comment]
Hi. thanks for your report. i am checking now.

**Comment by nimaltd** [comment]
It has been updated. please check again

**Comment by ElluIFX** [comment]
Work great, thanks @nimaltd

**Comment by nimaltd** [comment]
Your welcome
