### ISSUE TITLE
FLASH_BANK_1 undeclared

### ISSUE THREAD

**Issue by oscarpeters** [nimaltd/ee#31]
There seem to be an issue with:
`if (eeHandle.BankNumber == FLASH_BANK_1)` on line 161 in `ee.c`

it seems that the `FLASH_BANK_1` does not seem to be declared:
_'FLASH_BANK_1' undeclared (first use in this function); did you mean 'FLASH_BASE'?_

I am using a STM32WLE5x

**Comment by nimaltd** [comment]
Hi. I will be check on next week.

**Comment by nimaltd** [comment]
I have update the repository, please replace it in to your project and tell me the result. thanks.

**Comment by oscarpeters** [comment]
This seems to solve my problem. Thanks!
