### ISSUE TITLE
Compilation error in STM32L053

### ISSUE THREAD

**Issue by rajdeep-engineer** [nimaltd/ee#34]
In source file "ee.c", line number 227 of version 3.2.1, this line gives an error:-

flashErase.Page = eeHandle.PageSectorNumber;

I changed it to the following and it compiles now:-
flashErase.PageAddress = eeHandle.PageSectorNumber;

**Comment by nimaltd** [comment]
Thanks for reporting. I will fix it

**Comment by rajdeep-engineer** [comment]
Even though it compiled with the change I made, it doesn't report correctly.

In the screenshot, I stored uint32_t data of 8865, but what I get on reading is a different value. I think it is not selecting the last page of flash automatically. please help.
![image](https://github.com/user-attachments/assets/95c0e5a9-0875-47cd-a1bb-a463e393dd18)

**Comment by nimaltd** [comment]
Please change #define EE_ERASE EE_ERASE_PAGE_ADDRESS and try again.

**Comment by rajdeep-engineer** [comment]
now the value read is always 0
![image](https://github.com/user-attachments/assets/84772c37-f5e7-4191-833d-a1bbdc1759b6)

**Comment by nimaltd** [comment]
By a programmer, read flash and check the latest page address. 
And in debug, see the ee struct and tell me values

**Comment by rajdeep-engineer** [comment]
It's such a silly thing. I realized that STM32L0 and STM32L1 series microcontrollers have inbuilt EEPROM, so there is no need to emulate EEPROM using Flash memory. We can simply read-write to EEPROM using:-

void EEPROM_Write(uint32_t address, uint32_t data) {
    HAL_FLASHEx_DATAEEPROM_Unlock();
    HAL_FLASHEx_DATAEEPROM_Program(FLASH_TYPEPROGRAMDATA_WORD, address, data);
    HAL_FLASHEx_DATAEEPROM_Lock();
}

uint32_t EEPROM_Read(uint32_t address) {
    return *(uint32_t*)address;
}
